version: "3.7"
services:
  application:
    image: thomashennessy/triotaskapp
    ports:
    - target: 5000
    depends_on:
    - database
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
    deploy:
      replicas: 4
  nginx:
    image: nginx:latest
    depends_on:
    - application
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
  database:
    image: thomashennessy/triotaskdatabase
    ports:
    - target: 3306
      published: 3306
    volumes:
    - type: volume
      source: db_users
      target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
volumes:
  db_users:
