version: "3.7"
services:
  application:
    container_name: application
    build: ./flask-app
    ports:
    - target: 5000
    depends_on:
    - database
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
    - application
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
  database:
    container_name: database
    build: ./db
    ports:
    - target: 3306
      published: 3306
    volumes:
    - type: volume
      source: db_users
      target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
volumes:
  db_users:
